"""
Django settings for verify2_project project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '589mb0^%e7qgsm8y!%btvw9*m8#7h0i%+wj5!k*=k33xd5)0#%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ---------------------- Roland: DJANGO-TWILIO Settings: --------------------------

# Adding Twilio Account Credentials: (Roland's account)
# (found after logging into my Twilio account dashboard)
# SECURITY WARNING: recommended to keep these credentials secret for production! (i.e. remove them here)!
#                   Very bad for security in case this code is made public.
#                   Alternatively add the following insted using virtualenv to the end of /bin/activate.sh file:
#                           export TWILIO_ACCOUNT_SID=XXXXXXXXXXXXX
#                           export TWILIO_AUTH_TOKEN=YYYYYYYYYYYY
TWILIO_ACCOUNT_SID = 'AC09469fa56ea976ddab08fcb338c10c09' #required
TWILIO_AUTH_TOKEN = 'aecc734082ee5b7bf98d8326fb629d11'    #required

VERIFICATION_SID= 'VAf84aa43b79c7b6ded568d53525c1e2d8' # created verification service ID

# Sets a default callerid for the number clients receive smss or calls from.
# TWILIO_DEFAULT_CALLERID = 'AC09469fa56ea976ddab08fcb338c10c09' #optional

# If not set, this will always be the opposite of settings.DEBUG,
# so in production mode the forgery protection will be on,
# and in debug mode the protection will be turned off.

# If this setting is not present, it will default to the opposite of settings.DEBUG;
# In debug mode, forgery protection will be off,
# in production mode it will be on.
# Recommended to leave the protection off in debug mode.
# Important: Because of this, it is extremely important that when your site goes live,
#            you ensure that settings.DEBUG = False and
#            DJANGO_TWILIO_FORGERY_PROTECTION = True.
DJANGO_TWILIO_FORGERY_PROTECTION = False #optional, set to true for production!

# This setting will determine if django-twilio will run a database
# query comparing the incoming request 'from' attribute with any
# potential Caller objects in your database.
# DJANGO_TWILIO_BLACKLIST_CHECK = True #optional

# -------------------------------------------------------------------------------



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'verify.apps.VerifyConfig', # new

    'django_twilio', #new for django twilio
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'verify2_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # new
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'verify2_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] #new


